version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://backend:8080/api
      - VITE_OAUTH_LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
      - VITE_OAUTH_REDIRECT_URI=http://localhost:3000/auth/callback
      - VITE_JWT_PUBLIC_KEY_URL=http://backend:8080/.well-known/jwks.json
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ist-network

  backend:
    image: ist-auth-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
      - LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
    restart: unless-stopped
    networks:
      - ist-network

networks:
  ist-network:
    driver: bridge

volumes:
  postgres_data:
